@startuml DTLS_Server_Workflow
skinparam backgroundColor LightGrey
skinparam activity {
    StartColor YellowGreen
    EndColor Tomato
    BackgroundColor White
    ArrowColor Black
}
start

:Create UDP socket;
:Initialize WolfSSL;

if (Use PSK or Certificates?) then (PSK)
    :Set PSK identity and key;
else (Certificates)
    :Load Root CA;
    : Load server certificate and key;
endif

if (Use CID?) then (yes)
    :Generate random CID;
    :Enable CID for session;
else (no)
endif

:Accept DTLS handshake;
if (Handshake successful?) then (yes)
    :Store IP and port;
    repeat
        label receivepacket
        :Receive encrypted packet;
        if (CID enabled?) then (yes)
            :Compare stored IP with that of packet;
            if (IP or port changed?) then (yes)
                :Extract CID from packet;
                :Verify received CID matches stored CID;
                if (CID matches?) then (yes)
                    :Accept message;
                    :Update DTLS context to new IP;
                else (no)
                    label shutdown
                    :Shutdown session;
                    stop
                endif
            else (no)
            endif
            :Read and decrypt data using WolfSSL;
            :Parse received CoAP message;
            if (CoAP message is confirmable?) then (yes)
                :Extract Message ID and Token;
                :Construct and send CoAP acknowledgment;
            else (no)
                :Handle non-confirmable CoAP message;
            endif
        else (no)
            :Compare stored IP with that of packet;
            if (IP or port changed?) then (yes)
                :Reset DTLS session;
                :Update DTLS context to new IP;
                :Accept new DTLS handshake;
            else (no)
            endif
        endif
    repeat while
    detach
else (no)
    :Log handshake failure;
    :Shutdown DTLS session;
    stop
endif
@enduml